<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ashirbad" ignored="0" name="Test" tests="9" failures="2" timestamp="22 Aug 2019 19:17:05 GMT" time="0.082" errors="0">
  <testcase name="method1" time="0.015" classname="rerunningFailedTestcases.Caller">
    <skipped/>
  </testcase> <!-- method1 -->
  <testcase name="method1" time="0.003" classname="rerunningFailedTestcases.Caller">
    <skipped/>
  </testcase> <!-- method1 -->
  <testcase name="method1" time="0.003" classname="rerunningFailedTestcases.Caller">
    <skipped/>
  </testcase> <!-- method1 -->
  <testcase name="method1" time="0.001" classname="rerunningFailedTestcases.Caller">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at rerunningFailedTestcases.Caller.method1(Caller.java:10)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
  <testcase name="method2" time="0.001" classname="rerunningFailedTestcases.Caller">
    <skipped/>
  </testcase> <!-- method2 -->
  <testcase name="method2" time="0.0" classname="rerunningFailedTestcases.Caller">
    <skipped/>
  </testcase> <!-- method2 -->
  <testcase name="method2" time="0.001" classname="rerunningFailedTestcases.Caller">
    <skipped/>
  </testcase> <!-- method2 -->
  <testcase name="method2" time="0.001" classname="rerunningFailedTestcases.Caller">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at rerunningFailedTestcases.Caller.method2(Caller.java:15)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- method2 -->
  <testcase name="method3" time="0.001" classname="rerunningFailedTestcases.Caller"/>
</testsuite> <!-- Test -->
